### ISSUE TITLE
Get line positions in terms of x, y and width, height

### ISSUE THREAD

**Issue by netgfx** [JRIngram/maze-gen#79]
# Feature Request - *Insert suggest feature name here*
## Describe the feature
Ability to export coordinates of lines/walls in order to draw them. With the up,left,right, down system it is hard to draw lines for the walls.

Something like: 
```
[{x:0, y:0, width: 100, height:2}, {...}] would be preferable consolidating neighbor lines into one point so they can be drawn with `lineTo` or similar.

**Comment by JRIngram** [comment]
Apologies for taking a long while to get back on this.

I'm not quite sure what this request is asking for. Are you saying rather than using the up, left, right, down wall system coordinates for the walls should be used? 

I'm not sure how easy that would be to do, although it would probably be possible to do so by looping through the output of the `toJson` function for the maze?

Feel free to pick this up if you like, or feel free to expand on this. 

Again apologies for the delay in getting back.

**Comment by netgfx** [comment]
Hey there thanks for the response.

I made it like this (in case someone else comes looking)

```
makeBlocks() {
    var mazeLength = maze.length;
    for (var i = 0; i < mazeLength; i++) {
      for (var j = 0; j < maze[i].length; j++) {
        getBlockLines(maze[i][j], i);
      }
    }
  }

  function getBlockLines(cell, index) {

    var size = this.blockSize; // e.g 8
    if (cell.top) {
      var x1 = cell.x * size;
      var y1 = cell.y * size;
      var x2 = cell.x * size + size;
      var y2 = cell.y * size;
      drawLine(x1, y1, x2, y2);
    }
    if (cell.bottom) {
      double x1 = cell.x * size;
      double y1 = cell.y * size + size;
      double x2 = cell.x * size + size;
      double y2 = cell.y * size + size;

      drawLine(x1, y1, x2, y2, _paint);
    }
    if (cell.left) {
      var x1 = cell.x * size;
      var y1 = cell.y * size;
      var x2 = cell.x * size;
      var y2 = cell.y * size + size;

      drawLine(x1, y1, x2, y2,);
    }
    if (cell.right) {
      var x1 = cell.x * size + size;
      var y1 = cell.y * size;
      var x2 = cell.x * size + size;
      var y2 = cell.y * size + size;

      drawLine(x1, y1, x2, y2);
    }
  }
  ```
